---
title: "Final Project RMD"
author: "Jason Tran"
date: "2025-05-01"
output: html_document
---

### Loading in dataset to R and setup###
```{r}
library(tidyverse)
library(ggplot2)

setwd("C:/Users/Jason Derulo/Desktop/USF/Spring 2025/LIS 4317/Final Project")

covid_data <- read.csv("Covid data.csv")
population_data <- read.csv("US Population Data 2019.csv")
```

### Data Cleaning ###
```{r}
str(covid_data)
view(head(covid_data))

covid_data$Flag <- NULL
covid_data$ICD10_codes <- NULL
covid_data <- na.omit(covid_data)

population_data <- population_data %>%
  rename(State = STATE,
         Population = POPESTIMATE2019)

view(head(covid_data))

covid_data <- covid_data %>%
  rename("Deaths" = COVID.19.Deaths) %>%
  rename("Mentions" = Number.of.Mentions) %>%
  rename("Age" = Age.Group)

state_data <- covid_data %>%
  select(State, Deaths, Mentions, Condition) %>%
  group_by(State) %>%
  summarise(
    Covid_Deaths = sum(Deaths, na.rm = TRUE),
    Total_Mentions = sum(Mentions, na.rm = TRUE),
    Common_Condition = names(which.max(table(Condition))),
  ) %>%
  arrange(desc(Covid_Deaths))

state_data <- state_data %>%
  left_join(population_data %>% select(State, Population, lat, long), by = "State")

state_data <- state_data %>%
  filter(!State %in% c("United States", "Puerto Rico", "New York City", "District of Columbia"))
```

### Basic Visualizations ###
```{r}
view(state_data)

# Basic Plot
ggplot(state_data, aes(x = State, y = Covid_Deaths, fill = State)) +
  geom_bar(stat = "identity") +
  labs(
    title = "COVID Deaths by State",
    x = "State",
    y = "Covid Deaths") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_text(size = 12, face = "bold"),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5)
  )

# Deaths per capita
state_data$deaths_per_capita <- (state_data$Covid_Deaths / state_data$Population) * 100000

ggplot(state_data, 
       aes(x = State, y = deaths_per_capita, fill = State)) +
  geom_bar(stat = "Identity") +
  labs(title = "Covid Deaths per 100,000 People",
       x = "State",
       y = "Deaths / 100,000 People") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_text(size = 12, face = "bold"),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5)
  )

# Linear Regression Models
ggplot(state_data, aes(x = Population, y = deaths_per_capita)) +
  geom_point(aes(color = Total_Mentions), size = 3) +
  geom_smooth(method = "lm", color = "green") +
  scale_color_gradientn(colors = rainbow(3)) +
  scale_x_log10() + labs(title = "Covid Deaths LM",
       x = "Population",
       y = "Deaths per 100k") +
  theme(plot.title = element_text(hjust = 0.5))

ggplot(state_data, aes(x = deaths_per_capita, y = Covid_Deaths)) +
  geom_point(aes(size = Population, color = State)) +
  geom_smooth(method = "lm", color = "green") +
  labs(title = "Total Deaths vs Deaths per Capita",
       x = "Total Covid Deaths",
       y = "Deaths per 100,000 people",
       size = "Population",
       color = "Region") +
  theme(plot.title = element_text(hjust = 0.5))
```
